### ISSUE TITLE
How to understand "the representations of the two domains have the same ground truth"?

### ISSUE THREAD

**Issue by 4Statistics** [yueatsprograms/uda_release#4]
In the second paragraph，the author said  "under the reasonable assumption that the representations of the two domains have the same ground truth"?
How to understand this "reasonable assumption"?
How to understand "representations"?
Thank you very much.

**Comment by yueatsprograms** [comment]
Sorry I never ended up replying: "representations" just means features, like in an intermediate layer; I thought this assumption is "reasonable" because it's pretty standard in domain adaptation and probably holds for all the experimental datasets.

**Comment by yueatsprograms** [comment]
Answered.
