### ISSUE TITLE
Can you provide the code for testing on the cityscapes dataset?

### ISSUE THREAD

**Issue by ALEX13679173326** [yueatsprograms/uda_release#5]
Thanks for your paper and codes.
I have been confused for days about how to do experiments on GTA5 and cityscapes datasets.So,can you show me the code for doing self-supervised learning experiments on these dataset?

**Comment by yueatsprograms** [comment]
The link should be in the paper.

**Comment by ALEX13679173326** [comment]
OK!
Thank you very much!

**Comment by yueatsprograms** [comment]
Answered.
