### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by stes** [yueatsprograms/uda_release#7]
Dear authors, thanks a lot for sharing this reference implementation! I was wondering if you could clarify if you intended to release this code under [No License](https://choosealicense.com/no-permission/) or if it is possible to make the codebase available under an open source licence (e.g. MIT, Apache 2.0, ...) and add a LICENSE file to the repo.

Thanks for consideration!

**Comment by yueatsprograms** [comment]
The code is in public domain. Please feel free to do whatever you want.

**Comment by stes** [comment]
Hi @yueatsprograms , thanks for the fast response and allowing open usage of the code! I made a PR to the repo to reflect this also directly in the repo.
